title: Juan Manuel Castro Pérez # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Data Scientist, Ensenada, México
  <br><br>
  Mi objetivo es ayudar a las empresas en el manejo de datos para generar valor, de igual manera seguir aprendiendo y mejorando cada día.
  <br><br>
  Tengo experiencia en matematicas, estadistica, programación en python y R.
  <br><br>
  <a href="linkedin.com/in/juanmcp">Entra a mi perfil de LinkedIn</a> 
  <br><br>
  <a href="/pdf/plantilla-curriculum-blanco.pdf">Mira mi Curriculum Vitae (CV) </a> 
  
theme: jekyll-theme-minimal
