title: MBA. Juan Manuel Castro Pérez # your name (or website title) here
logo: "/images/pp.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Data Scientist, Ensenada, México
  <br><br>
  Mi objetivo es seguir creciendo en el ámbito de la Ciencia de Datos y aportar mis conocimientos en análisis de sistemas organizacionales complejos con enfoque en la toma de decisiones combinando mis conocimientos en la integración de sistemas complejos, finanzas y ciencia de datos. Liderando un equipo dinámico.
  <br><br>
  Tengo experiencia en matematicas, estadistica, programación en python, R, HTML, Java y CSS.
  <br><br>
  <a href="https://linkedin.com/in/juanmcp">Entra a mi perfil de LinkedIn</a> 
  <br><br>
  <a href="/pdf/cv.pdf">Mira mi Curriculum Vitae (CV) </a> 
  
theme: jekyll-theme-minimal
